version: "3.8"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=demo
    ports:
      - "5432:5432"
    networks:
      - bridgenetwork

networks:
  bridgenetwork:
    driver: bridge